require("prototypes.categories")
require("prototypes.fluid")
require("prototypes.item")
require("prototypes.sprite")
require("prototypes.entity")
require("prototypes.recipe")
require("prototypes.technology")
